specVersion: 1.0.0
name: kusama
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '>=1.0.0'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  This project can be use as a starting point for developing your SubQuery
  project
repository: 'https://github.com/subquery/subql-starter'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://kusama.api.onfinality.io/public-ws'
  dictionary: 'https://api.subquery.network/sq/subquery/kusama-dictionary'
  genesisHash: '0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe'
dataSources:
  - kind: substrate/Runtime
    startBlock: 11415420
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleSystemRemarkCall
          kind: substrate/CallHandler
          filter:
            module: system
            method: remark
            success: true
